name: Build assets
on:
  push:
    branches:
      - master

jobs:
  all:
    name: Build assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['10.x']
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Remove build and source files
        run: |
          rm -rf node_modules
          rm -rf development
          rm -rf src
      - name: Commit all changes
        run: |
          git config --global user.email "github-build-assets-bot@users.noreply.github.com"
          git config --global user.name "[BOT] Build Assets"
          git add -A --force dist/
          git commit -m "Asset build" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master-build
          force: true
